# Site settings
title: UX Portfolio of Vítor Teixeira
email: vsdteixeira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Vítor Teixeira is a User Experience Designer from Lisbon.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site
twitter_username: vsdteixeira
github_username:  vitor-teixeira
permalink: /:year/:month/:title.html
  
# Build settings
markdown: redcarpet
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
  js_compressor: 'uglifier'
  css_compressor: 'sass'
  cachebust: none
  gzip: [ text/css, application/javascript ]
  debug: false