# Site settings 
title: User Experience Portfolio of Vítor Teixeira
email: vsdteixeira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Virtual home of Vítor Teixeira's User Experience Portfolio. He's into User Research, Information Architecture, Responsive Web Design, and more.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vteixeira.com" # the base hostname & protocol for your site
twitter_username: vsdteixeira
github_username:  vitor-teixeira
permalink: /:categories/:year/:month/:title.html
gems:
 - jekyll-sitemap
  
# Build settings
markdown: redcarpet
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
  js_compressor: 'uglifier'
  css_compressor: 'sass'
  cachebust: none
  gzip: [ text/css, application/javascript ]
  debug: false